version: '2.1'

services:
  project-db-ui:
    image: project-db-ui
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8082:80
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js
